[package]

name = "maidsafe_vault"
version = "0.0.3"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://dirvine.github.io/maidsafe_vault/"
repository = "https://github.com/dirvine/maidsafe_vault"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://www.maidsafe.net"

[dependencies]
rustc-serialize = "*"
cbor = "*"
time = "*"
sodiumoxide = "0.0.4"
rand = "*"
[dependencies.routing]
path="../routing"
[dependencies.maidsafe_types]
path="../maidsafe_types"
